version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - LINEAR_CLIENT_ID=${LINEAR_CLIENT_ID}
      - LINEAR_CLIENT_SECRET=${LINEAR_CLIENT_SECRET}
      - LINEAR_REDIRECT_URI=${LINEAR_REDIRECT_URI}
      - CONFLUENCE_CLIENT_ID=${CONFLUENCE_CLIENT_ID}
      - CONFLUENCE_CLIENT_SECRET=${CONFLUENCE_CLIENT_SECRET}
      - APP_URL=${APP_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/linear_agent
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - PORT=3000
      - CONFLUENCE_CLIENT_ID=${CONFLUENCE_CLIENT_ID}
      - CONFLUENCE_CLIENT_SECRET=${CONFLUENCE_CLIENT_SECRET}
      - APP_URL=${APP_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - CONFLUENCE_USERNAME=${CONFLUENCE_USERNAME}
      - CONFLUENCE_API_TOKEN=${CONFLUENCE_API_TOKEN}
      - CONFLUENCE_BASE_URL=${CONFLUENCE_BASE_URL}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - SQLITE_DB_PATH=/app/data/sync.db
      - NODE_ENV=production
    volumes:
      - sqlite_data:/app/data
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=linear_agent
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  sqlite_data:
